name: "\U0001F41E Bug report"
description: Create a report to help us improve
labels:
  - bug
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Logs
      render: shell

  - type: textarea
    attributes:
      label: Additional information
      description: Add any other information about the problem here.
